[package]
name = "pcics"
version = "0.1.0"
authors = ["mbratchikov"]
edition = "2021"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
regex = "1.5"
modular-bitfield = "0.11.2"
byte = "0.2.6"
displaydoc = "0.2.3"

[dev-dependencies]
pretty_assertions = "0.7"
